### PR TITLE
Reset message count and only add new messages on refresh.

### PR DESCRIPTION
**Pull request by DJaeger**
Fixes nerzhul/ocsms#117

### CODE REVIEW

**Comment by nerzhul** [comment]
thanks for the commit; g_lastMsgDate is use to refresh the contact list message count too. If we reset it when opening conversation this will trigger reset of the contact list message count too. But this could be acceptable, i will think about this

**Comment by nerzhul** [comment]
Testing it now

**Comment by nerzhul** [comment]
That does the trick, i merge it and i will adapt another thing after this merge

**Comment by DJaeger** [comment]
:+1:

**Comment by nerzhul** [comment]
i'm also fixing another thing by changing one data stored into database, this permit to cleanup the database model & php code

**Pull request merged**
