### PR TITLE
Fix SyntaxErrorException on select limit

### PR DESCRIPTION
**Pull request by yneveu**
Your patch for https://github.com/nerzhul/ocsms/issues/140 didn't fix issue for me but this change i made fix it. It makes use of the "limit" prepare function.

### CODE REVIEW

**Comment by nerzhul** [comment]
@yneveu are you sure it's right ? you pass limit at first prepare argument then i think it should replace the first "?"

**Comment by yneveu** [comment]
No, it's the second argument of prepare().
According to https://doc.owncloud.org/api/classes/OCP.DB.html#method_prepare it sets a limit to query. Maybe i'm wrong but it's seems to replace a limit in the query string.

**Comment by nerzhul** [comment]
@yneveu interesting, i will test this on postgresql before merge, thanks for highlighting this point

**Comment by nerzhul** [comment]
Okay i tested it in pgsql, you need to remove LIMIT ? from the query, can you do this after i will merge

**Comment by yneveu** [comment]
Of course yes ....
Done

**Pull request merged**
