### PR TITLE
adding additional metadata?

### PR DESCRIPTION
**Pull request by martin-rueegg**
how about adding additional metadata?

### CODE REVIEW

**Comment by nerzhul** [comment]
Where does those metadata are used ?

Please rebase without bumping the version, i do it myself when it's ready.

**Comment by martin-rueegg** [comment]
(sorry about the version. - sure! - fixed)

i did not see where the website and bugs-info is posted. probably on apps.owncloud.com if it's there.
the following information would be shown in /index.php/settings/apps
```
    <documentation>
        <user>http://doc.owncloud.org</user>
        <admin>http://doc.owncloud.org</admin>
    </documentation>
```
but i don't know if there is any documentation page.

i got the info from:
http://doc.owncloud.org/server/8.0/developer_manual/app/info.html

and the ocsid is saved to the db-table PREFIX_appconfig and probably helps for getting updates (i can now see there is an update available, but updating fails. not sure yet why.)

**Comment by nerzhul** [comment]
Good news then. Could you rebase your commits ?

git rebase -i HEAD~2

**Comment by martin-rueegg** [comment]
well, it's my first time i use git ever. so sorry if i did some things wrong. but as i understand it, the version here is now correct. anything i need to do in order that you can accept the pull request?

**Comment by nerzhul** [comment]
you need to squash your commits.
To do this, please do git rebase -i HEAD~4 and replace pick by s into the 3 last commits and close the file.
Then merge the commit texts and close
Finally push to your patch branch adding --force.

**Comment by martin-rueegg** [comment]
thanks! - like this?

**Comment by nerzhul** [comment]
It seems you squash your commit with my previous commit, it's wrong :(
i think the best for you is to:
- git reset --hard <last master commit it>
- redo you change,
- repush with force
Last master commit is the sha trace into the github master branch

**Comment by martin-rueegg** [comment]
sorry for all the mess. i couldn't work out what you suggested.  now the changes here in the pull request reflect only my additions. i hope now it's ok.

**Comment by nerzhul** [comment]
ouch, i'll merge it myself and squash it.

**Comment by nerzhul** [comment]
Commit: eeb2f579018aae71cb1722036fa004cbad902822

Thanks for your contribution.

**Comment by martin-rueegg** [comment]
your welcome. and thanks for your patience. will see that i learn more about git! :-)

**Pull request closed without merging**
